steps:
# Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA', '.']
  id: Build

# Push Docker image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']
  id: Push

# Deploy to GKE
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/flask-app', 'flask-app=gcr.io/$PROJECT_ID/flask-app:$SHORT_SHA']
  id: Deploy
  waitFor:
    - Push

# Rollout status check
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['rollout', 'status', 'deployment/flask-app']
  id: RolloutStatus
  waitFor:
    - Deploy
